name       : xorg-xwayland
version    : 24.1
release    : 25
source     :
    - https://xorg.freedesktop.org/archive/individual/xserver/xwayland-24.0.99.902.tar.xz : a61f88ad90aac5acdc1bf2f682d23bf297cf2fec9a71027dff3806ffd5995e03
license    : MIT
component  : xorg.server
homepage   : https://www.x.org/
summary    : X server intended for Xorg only clients to run under Wayland for backwards compatability.
description: |
    X server intended for Xorg only clients to run under Wayland for backwards compatability.
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(epoxy)
    - pkgconfig(fontutil)
    - pkgconfig(gdm)
    - pkgconfig(inputproto)
    - pkgconfig(libdecor-0)
    - pkgconfig(libdrm)
    - pkgconfig(libei-1.0)
    - pkgconfig(libtirpc)
    - pkgconfig(libxcvt)
    - pkgconfig(nettle)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-eglstream-protocols)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xfont2)
    - pkgconfig(xkbcomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xshmfence)
    - pkgconfig(xtrans)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Provided by xorg-server
    rm -fr $installdir/usr/lib64/xorg/
    rm $installdir/usr/share/man/man1/Xserver.1
patterns   : /*
