name       : gnome-software
version    : '46.1'
release    : 8
source     :
    - https://download.gnome.org/sources/gnome-software/46/gnome-software-46.1.tar.xz : b6eeb789100de94b50ebe2e77f16b26be4c2db15489905f198d060c425e19076
homepage   : https://apps.gnome.org/Software/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME Software allows users to easily find, discover and install apps.
description: |
    GNOME Software allows users to easily find, discover and install apps. It also keeps their OS, apps and devices up to date without them having to think about it, and gives them confidence that their system is up to date. It supports popular distributions, subject to those distributions maintaining their own distro-specific integration code.
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(flatpak)
    - pkgconfig(fwupd)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(packagekit-glib2)
    - pkgconfig(xmlb)
    - gtk-doc
setup      : |
    # reenable me!
    #patch -p1 -i $pkgfiles/0001-gs-appstream-Check-against-kernel-relation-types.patch
    %patch -p1 -i $pkgfiles/0001-packagekit-Hardcode-some-solus-thingies.patch
    %meson_configure \
        -Dpackagekit_autoremove=true \
        -Dmalcontent=false \
        -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 $pkgfiles/org.gnome.software.gschema.override $installdir/usr/share/glib-2.0/schemas/org.gnome.software.gschema.override
