name       : mesalib
version    : 24.1.0
release    : 231
source     :
    - https://mesa.freedesktop.org/archive/mesa-24.1.0-rc2.tar.xz : fc7d3589735dfeed2955415111554d4f8721b1b0f700a9e282680aa178d4cd1c
homepage   : http://mesa3d.org/
license    :
    - BSL-1.0
    - MIT
    - SGI-B-1.0
component  : xorg.display
summary    : Mesa is an OpenGL compatible 3D graphics library.
description: |
    Mesa is an OpenGL compatible 3D graphics library.
emul32     : yes
libsplit   : no
networking : yes
builddeps  :
    - pkgconfig32(LLVMSPIRVLib)
    - pkgconfig32(SPIRV-Tools)
    - pkgconfig32(expat)
    - pkgconfig32(libdrm)
    - pkgconfig32(libelf)
    - pkgconfig32(libglvnd)
    - pkgconfig32(libudev)
    - pkgconfig32(libunwind)
    - pkgconfig32(libva)
    - pkgconfig32(libzstd)
    - pkgconfig32(nettle)
    - pkgconfig32(vdpau)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xcb-dri3)
    - pkgconfig32(xcb-keysyms)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
    - pkgconfig32(xrandr)
    - pkgconfig32(xshmfence)
    - pkgconfig32(xxf86vm)
    - pkgconfig32(zlib)
    - pkgconfig(libclc)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xproto)
    - cbindgen
    - git
    - glslang-devel
    - llvm-32bit-devel
    - llvm-clang-32bit-devel
    - lm_sensors-devel
    - mako
    - python-ply
    - rust
    - rust-bindgen
rundeps    :
    - 32bit :
        - libglvnd-32bit
    - 32bit-devel :
        - libglvnd-32bit-devel
    - devel :
        - libglvnd-devel
    - libglvnd
    - linux-driver-management
clang      : yes
optimize   :
    - no-symbolic
    # - thin-lto
environment: |
    export PYTHON=/usr/bin/python3

    export PE_CODECS=0
    if [[ ! -z $PE_CODECS ]]; then
          export PT_ARGS="-Dvideo-codecs=all"
    else
          export PT_ARGS=""
    fi
setup      : |
    if [[ ! -z $EMUL32BUILD ]]; then
          export EXTRA_ARGS="--cross-file $pkgfiles/llvm32.native --libdir=/usr/lib32"
    else
          export EXTRA_ARGS=""
    fi
    %meson_configure \
        $EXTRA_ARGS \
        $PT_ARGS \
        -Degl=enabled \
        -Dgallium-drivers=crocus,iris,nouveau,r300,r600,radeonsi,svga,swrast,virgl,zink \
        -Dgallium-extra-hud=true \
        -Dgallium-nine=true \
        -Dgallium-va=enabled \
        -Dgallium-vdpau=enabled \
        -Dgallium-xa=enabled \
        -Dgbm=enabled \
        -Dgles1=disabled \
        -Dglvnd=true \
        -Dintel-clc=enabled \
        -Dllvm=enabled \
        -Dmicrosoft-clc=disabled \
        -Dosmesa=true \
        -Dplatforms=x11,wayland \
        -Dvulkan-drivers=amd,intel,intel_hasvk,nouveau,swrast,virtio \
        -Dvulkan-layers=device-select,overlay
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Add missing symlink
    ln -s libGLX_mesa.so.0 $installdir/%libdir%/libGLX_indirect.so.0
patterns   :
    - devel :
        - /usr/lib64/lib*GL.so
        - /usr/lib64/libGL*.so
        - /usr/lib64/libOS*.so
        - /usr/lib64/libg*.so
        - /usr/lib64/libwayland*.so
        - /usr/lib64/libxa*.so
    - 32bit-devel :
        - /usr/lib32/lib*GL.so
        - /usr/lib32/libGL*.so
        - /usr/lib32/libOS*.so
        - /usr/lib32/libg*.so
        - /usr/lib32/libwayland*.so
        - /usr/lib32/libxa*.so
