name       : resynthesizer
version    : 2.0.3
release    : 4
source     :
    - https://github.com/bootchk/resynthesizer/archive/v2.0.3.tar.gz : 798678095c34b101c880eb350b31e9a6ff9748707d6ad9063cdee26c38016450
homepage   : https://github.com/bootchk/resynthesizer
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A set of plugins for the GIMP image editing app
description: |
    A set of plugins for the GIMP image editing app
builddeps  :
    - pkgconfig(gimp-2.0)
    - pkgconfig(gtk+-2.0)
    - gettext-devel
    - intltool
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
