name       : xfce4-clipman-plugin
version    : 1.6.6
release    : 1
source     :
    - https://archive.xfce.org/src/panel-plugins/xfce4-clipman-plugin/1.6/xfce4-clipman-plugin-1.6.6.tar.bz2 : 08ad475b006f878df5dd20d83c98edc33ed21e69b414d0e5ff6d4accd64d7120
homepage   : https://docs.xfce.org/panel-plugins/xfce4-clipman-plugin/start
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Clipman is a clipboard manager for Xfce.
description: |
    Clipman is a clipboard manager for Xfce. It keeps the clipboard contents around while it is usually lost when you close an application. It is able to handle text and images, and has a feature to execute actions on specific text by matching them against regular expressions.
builddeps  :
    - pkgconfig(libxfce4panel-2.0)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libxfce4util-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
