name       : sof-firmware
homepage   : https://github.com/thesofproject/sof-bin
version    : '2.9'
release    : 17
source     :
    - https://github.com/thesofproject/sof-bin/releases/download/v2024.03/sof-bin-2024.03.tar.gz : 4fd932f7bbc1517b06fa7911e6d566814d5dc4fec5608bdb44e7c4fe4929fbf6
license    :
    - BSD-3-Clause
    - ISC
component  : kernel
summary    : Sound Open Firmware
description: |
    Sound Open Firmware
install    : |
    install -dm00755 $installdir/lib/firmware/intel
    cp -a sof "$installdir/lib/firmware/intel/sof"
    cp -a sof-ace-tplg "$installdir/lib/firmware/intel/sof-ace-tplg"
    cp -a sof-ipc4 "$installdir/lib/firmware/intel/sof-ipc4"
    cp -a sof-ipc4-tplg "$installdir/lib/firmware/intel/sof-ipc4-tplg"
    cp -a sof-tplg "$installdir/lib/firmware/intel/sof-tplg"
    install -Dm00644 $pkgfiles/sof-firmware.metainfo.xml $installdir/usr/share/metainfo/sof-firmware.metainfo.xml
